services:
  common:
    labels:
      application: smartface
  sf-cam:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-cam:${SF_VERSION}
    container_name: SFCam1
    labels:
      scrapeMetrics: true
    command: --serviceName SFCam1
      #ports:
      #  - 30001:${CameraDefaults__PreviewPort}
    expose:
      - 4318
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - NoSqlDataStorageDisabled
      - SF_FACE_TEMPLATE_COMPATIBILITY_VERSION=1.40
    # - GstPipelineTemplate
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - ./iengine.lic:/etc/innovatrics/iengine.lic
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia