version: "3.7"
services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:16.1.1
    container_name: keycloak-server
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=https://presales-demo-1u.ba.innovatrics.net/auth
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    command:
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=singleFile
      - -Dkeycloak.migration.file=/tmp/realm-export.json
      - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING

networks:
  default:
    name: sf-network
    external: true
