version: '3'
services:

  rabbitmq:
    image: "rabbitmq:3.10.2-management"
    container_name: rmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
    environment: 
      RABBITMQ_NODENAME: rabbit@rmq
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/external/rabbitmq.conf
    volumes:
      - ./etc_rmq/:/etc/rabbitmq/external
      - rmqdata:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rmqdata:

networks:
  default:
    external:
      name: sf-network
