version: "3.4"
services:
  sf-base:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-base:${SF_VERSION}
    container_name: SFBase
    labels:
      scrapeMetrics: true
    command: --serviceName SFBase
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      - 2406:2406
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  sf-streamdatadbworker:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-streamdatadbworker:${SF_VERSION}
    container_name: SFStreamDataDbWorker
    labels:
      scrapeMetrics: true
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  api:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-api:${SF_VERSION}
    container_name: SFApi
    labels:
      scrapeMetrics: true
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - MQTT__Hostname
      - MQTT__Username
      - MQTT__Password
      - MQTT__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - NoSqlDataStorageDisabled
      - CameraDefaults__PreviewPort
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  sf-graphql-api:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-graphql-api:${SF_VERSION}
    container_name: SFGraphQLApi
    labels:
      scrapeMetrics: true
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      # we forward the configured ports to default SF ports
      - 8097:${Hosting__Port}
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - MQTT__Hostname
      - MQTT__Username
      - MQTT__Password
      - MQTT__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  odata-api:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-odata-api:${SF_VERSION}
    container_name: SFODataApi
    labels:
      scrapeMetrics: true
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      # we forward the configured ports to default SF ports
      - 8099:${Hosting__Port}
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  detector:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-detector:${SF_VERSION}
    container_name: SFDetectCpu
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      # - Gpu__GpuEnabled=true
      # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia

  extractor:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-extractor:${SF_VERSION}
    container_name: SFExtractCpu
    labels:
      scrapeMetrics: true
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      # - Gpu__GpuEnabled=true
      # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia

  matcher:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-matcher:${SF_VERSION}
    container_name: SFWatchlistMatcher
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    cpuset: "0"

  face-matcher:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-face-matcher:${SF_VERSION}
    container_name: SFFaceMatcher
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  liveness:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-liveness:${SF_VERSION}
    container_name: SFLiveness
    labels:
      scrapeMetrics: true
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - Serilog__MinimumLevel__Default=Warning
      - JAEGER_AGENT_HOST
      # - Gpu__GpuEnabled=true
      # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia

  edge-stream-processor:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-edge-stream-processor:${SF_VERSION}
    container_name: SFEdgeStreamProcessor
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_RabbitMq_Enabled
      - Serilog__MinimumLevel__Default=Warning
      - NoSqlDataStorageDisabled
      - OperationMode__MatchingDataStrategy
      - OperationMode__LivenessDataStrategy
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  edge-streams-state-synchronizer:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-edge-streams-state-synchronizer:${SF_VERSION}
    container_name: SFEdgeStreamsStateSynchronizer
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - RabbitMQ__StreamsPort
      - MQTT__Hostname
      - MQTT__Username
      - MQTT__Password
      - MQTT__Port
      - MQTT__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_RabbitMq_Enabled
      - Serilog__MinimumLevel__Default=Warning
      - Rpc__TimeoutMs
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  access-controller:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-access-controller:${AC_VERSION}
    container_name: SFAccessController
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      # we forward the configured ports to default SF ports
      - 5050:${Hosting__Port}
    privileged: true
    restart: unless-stopped
    environment:
      - RabbitMq__HostName=${RabbitMQ__Hostname}
      - RabbitMq__UserName=${RabbitMQ__Username}
      - RabbitMq__Password=${RabbitMQ__Password}
      - RabbitMq__Port=${RabbitMQ__Port}
      - RabbitMq__VirtualHost=${RabbitMQ__VirtualHost}
      - RabbitMq__UseSsl=${RabbitMQ__UseSsl}
      - Kestrel__EndPoints__Http__Url=${Hosting__Host}:${Hosting__Port}
      - Serilog__MinimumLevel__Default=Warning
      - MQTT__Hostname
      - MQTT__Username
      - MQTT__Password
      - MQTT__Port
      - MQTT__UseSsl
    env_file: .env.sfac

  sf-station:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-station:${SFS_VERSION}
    container_name: SFStation
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file: .env.sfstation

  access-control-connector:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}integrations-access-control-connector
    restart: unless-stopped
    env_file: .env.actrlcon

networks:
  default:
    external:
      name: sf-network
