# TODO: Discuss with SFIT need for privileged: true, synchronize logging, why is access-control-connector different?

services:
  sf-base:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-base:${SF_VERSION}
    command: --serviceName SFBase
    ports:
      - 2406:2406
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  sf-streamdatadbworker:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-streamdatadbworker:${SF_VERSION}
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  api:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-api:${SF_VERSION}
    ports:
      - 8098:80
    environment:
      MQTT__Hostname:
      MQTT__Username:
      MQTT__Password:
      MQTT__Port:
      MQTT__UseSsl:
      CameraDefaults__PreviewPort:
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  sf-graphql-api:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-graphql-api:${SF_VERSION}
    labels:
      scrapeMetrics: true
    ports:
      - 8097:80
    expose:
      - 4318
    environment:
      MQTT__Hostname:
      MQTT__Username:
      MQTT__Password:
      MQTT__Port:
      MQTT__UseSsl:
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  odata-api:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-odata-api:${SF_VERSION}
    ports:
      - 8099:80
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  detector:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-detector:${SF_VERSION}
    #environment:
    # Gpu__GpuEnabled: true
    # Gpu__GpuNeuralRuntime: Tensor
    #volumes:
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  extractor:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-extractor:${SF_VERSION}
    labels:
      scrapeMetrics: true
    expose:
      - 4318
    #environment:
    # Gpu__GpuEnabled: true
    # Gpu__GpuNeuralRuntime: Tensor
    #volumes:
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  matcher:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-matcher:${SF_VERSION}
    cpuset: "0"
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  face-matcher:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-face-matcher:${SF_VERSION}
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  liveness:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-liveness:${SF_VERSION}
    labels:
      scrapeMetrics: true
    expose:
      - 4318
    #environment:
    #   - Gpu__GpuEnabled=true
    #   - Gpu__GpuNeuralRuntime=Tensor
    #volumes:
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  edge-stream-processor:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-edge-stream-processor:${SF_VERSION}
    environment:
      NoSqlDataStorageDisabled:
      Serilog__MinimumLevel__Default: Warning
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  edge-streams-state-synchronizer:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-edge-streams-state-synchronizer:${SF_VERSION}
    environment:
      MQTT__Hostname:
      MQTT__Username:
      MQTT__Password:
      MQTT__Port:
      MQTT__UseSsl:
      Rpc__TimeoutMs:
      Serilog__MinimumLevel__Default: Warning
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  access-controller:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-access-controller:${AC_VERSION}
    ports:
      - 5050:80
    environment:
      MQTT__Hostname:
      MQTT__Username:
      MQTT__Password:
      MQTT__Port:
      MQTT__UseSsl:
      Kestrel__EndPoints__Http__Url: http://+:80
      Serilog__MinimumLevel__Default: Warning
    env_file: .env.sfac
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  sf-station:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-station:${SFS_VERSION}
    ports:
      - 8000:8000
    env_file: .env.sfstation
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    privileged: true

  access-control-connector:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}integrations-access-control-connector
    env_file: .env.actrlcon

networks:
  default:
    external:
      name: sf-network
