services:

  sf-base:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-base:${SF_VERSION}
    command: --serviceName SFBase
    ports:
      - 2406:2406

  sf-group:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-grouping:${SF_VERSION}
    command: --serviceName SFGroup

  sf-streamdatadbworker:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-streamdatadbworker:${SF_VERSION}

  api:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-api:${SF_VERSION}
    ports:
      - 8098:80
    environment:
      MQTT__Hostname:
      MQTT__Username:
      MQTT__Password:
      MQTT__Port:
      MQTT__UseSsl:
      Hosting__Host: http://+
      Hosting__Port: 80
      CameraDefaults__PreviewPort:

  sf-graphql-api:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-graphql-api:${SF_VERSION}
    labels:
      scrapeMetrics: true
    ports:
      - 8097:80
    expose:
      - 4318
    environment:
      MQTT__Hostname:
      MQTT__Username:
      MQTT__Password:
      MQTT__Port:
      MQTT__UseSsl:
      Hosting__Host: http://+
      Hosting__Port: 80

  odata-api:
    extends:
      service: common-rabbitmq-db-s3-scrapeMetrics
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-odata-api:${SF_VERSION}
    ports:
      - 8099:80
    environment:
      Hosting__Host: http://+
      Hosting__Port: 80

  detector:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-detector:${SF_VERSION}
    #environment:
    # Gpu__GpuEnabled: true
    # Gpu__GpuNeuralRuntime: Tensor
    #volumes:
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia
  
  extractor:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-extractor:${SF_VERSION}
    labels:
      scrapeMetrics: true
    expose:
      - 4318
    #environment:
    # Gpu__GpuEnabled: true
    # Gpu__GpuNeuralRuntime: Tensor
    #volumes:
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    #runtime: nvidia

  matcher:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-matcher:${SF_VERSION}
    cpuset: "0"

  face-matcher:
    extends:
      service: common-rabbitmq-db
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-face-matcher:${SF_VERSION}

  sf-station:
    extends:
      service: common
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-station:${SFS_VERSION}
    ports:
      - 8000:8000
    env_file: .env.sfstation

  db-synchronization-leader:
    extends:
      service: common-rabbitmq
      file: docker-compose-common.yml
    image: ${REGISTRY}sf-db-synchronization-leader:${SF_VERSION}
    ports:
      - 8100:${Hosting__Port}
    environment:
      Hosting__Host:
      Hosting__Port:
      S3Bucket__Endpoint:
      S3Bucket__BucketName:
      S3Bucket__AccessKey:
      S3Bucket__SecretKey:
      Authentication__UseAuthentication:
      Authentication__IgnoreHttpsIssuerCheck:
      Authentication__Authority:
      Authentication__Audience:

networks:
  default:
    external:
      name: sf-network
