version: '3.4'
services:
  detector:
    image: ${REGISTRY}sf-detector:${SF_VERSION}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
         
  extractor:
    image: ${REGISTRY}sf-extractor:${SF_VERSION}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
      
  matcher:
    image: ${REGISTRY}sf-matcher:${SF_VERSION}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
      
  watchlist-api:
    image: ${REGISTRY}sf-watchlist-api:${SF_VERSION}
    container_name: SFWatchlistApi
    ports: 
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
      

networks:
  default:
    external:
      name: sf-network