version: '3.4'
services:
  detector:
    image: ${REGISTRY}sf-jetson-detector:${VERSION}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia
         
  extractor:
    image: ${REGISTRY}sf-jetson-extractor:${VERSION}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia
      
  matcher:
    image: ${REGISTRY}sf-jetson-matcher:${VERSION}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia
      
  watchlist-api:
    image: ${REGISTRY}sf-jetson-watchlist-api:${VERSION}
    container_name: SFWatchlistApi
    ports: 
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      volumes:
        - "./iengine.lic:/etc/innovatrics/iengine.lic"
      runtime: nvidia

networks:
  default:
    external:
      name: sf-network