version: '3'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
  pgsql:
    image: "postgres:13.2"
    container_name: pgsql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Test1234
  pgadmin:
    image: "dpage/pgadmin4:5.1"
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Test1234
    ports:
      - "7070:80"
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rmq
    ports:
      - "15672:15672"
      - "5672:5672"
  minio:
    image: "minio/minio:RELEASE.2021-02-01T22-56-52Z"
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"
networks:
  default:
    name: sf-network
