{
 "title": "Investigation examples",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_duration_ms_count[$__rate_interval])) by (rpc_operation, processing_unit)",
     "legendFormat": "{{rpc_operation}}-{{processing_unit}}"
    }
   ]
  },
  {
   "title": "ZeroMQ notifications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(smartface_zeromq_notifications_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ZeroMQ pings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(smartface_zeromq_pings_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 33 },
     "targets": [
      { "service": "SFWatchlistMatcher" }
     ]
    }
   ]
  },
  {
   "title": "Generic metrics (CPU, Memory)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "SF Services CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "100 * sum(rate(container_cpu_usage_seconds_total{application=\"app_x_smartface\"}[1m])) by (composeservice)",
       "legendFormat": "{{dockerservice}}"
      }
     ]
    },
    {
     "title": "SF Services memory usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{application=\"app_x_smartface\"}",
       "legendFormat": "{{composeservice}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "SF Services logs",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "{application=\"app_x_smartface\"} | json | line_format \"{{.ServiceName}} {{._mt}} {{._x}}\""
      }
     ]
    },
    {
     "title": "SF Services logs - filter by service and string",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "{application=\"app_x_smartface\",composeservice=\"detector\"} | json | line_format \"{{.ServiceName}} {{._mt}} {{._x}}\" |~ \"Detected\""
      }
     ]
    }
   ]
  }
 ]
}