version: "3.6"

services:
  obsminio:
    image: "minio/minio"
    command: server /data --console-address ":9001"
    expose:
      - 9000
    ports:
      - "9901:9001"
    volumes:
      - minio_data:/data
    networks:
      observability:
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.4
    ports:
      - 9900:3000
    volumes:
      - ./configuration/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configuration/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      observability:
      sf-network:
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.1
    depends_on:
      obsminio:
        condition: service_started
      obsminio_createbuckets:
        condition: service_completed_successfully
    volumes:
      - ./configuration/loki:/etc/loki
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    expose:
      - 3100
    networks:
      observability:
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.1
    depends_on:
      loki:
        condition: service_started
    volumes:
      - ./configuration/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    # to debug relabeling, additional command line arguments "--dry-run --inspect" can be used
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      observability:
    restart: unless-stopped

  # Jaeger tracing as configured here is solely for debug purposes. No data is stored!
  jaeger:
    image: "jaegertracing/all-in-one:1.39.0"
    command: [ "--memory.max-traces=5000" ]
    expose:
      - 5778
      - 16686
      - 14268
      - 14250
      - 9411
      - 5775
      - 6831
      - 6832
    ports:
      - "9903:16686"
    networks:
      sf-network:
        aliases:
          - jaeger
      observability:
    restart: unless-stopped

  nodeexporter:
    image: prom/node-exporter:v1.6.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      observability:
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      observability:
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./configuration/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    user: root
    expose:
      - 9090
    ports:
      - 9902:9090
    networks:
      observability:
      sf-network:
    restart: unless-stopped

volumes:
  minio_data: #obs_grafana_datasources:

  #obs_grafana_dashboards:
  grafana_data: #obs_loki_config:

  loki_data: #obs_promtail_config:

  #obs_prometheus_config:
  prometheus_data:

networks:
  observability:
  sf-network:
    external:
      name: sf-network
