{
 "title": "SFIT - Dashboard RAMONLY",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info,namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\"},rabbitmq_cluster)"
    }
   },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "text",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:orange\">\r\n<font size=\"50\">$hostname</font>\r\n</div>"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{hostname=\"$hostname\", instance=\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Ram Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "stat",
   "description": "Used Swap",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "RMQ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{hostname=\"$hostname\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Messages ready",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{hostname=\"$hostname\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "stat",
   "description": "Used Root FS",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{hostname=\"$hostname\", instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{hostname=\"$hostname\", instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RMQ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{hostname=\"$hostname\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Messages pending",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{hostname=\"$hostname\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{hostname=\"$hostname\", instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "SmartFace Services",
   "type": "stat",
   "gridPos": { "h": 18, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{hostname=\"$hostname\", application=\"smartface\"}",
     "legendFormat": "{{dockerservice}}"
    }
   ]
  },
  {
   "title": "Dependencies",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{hostname=\"$hostname\", application=\"smartface_dependencies\"}",
     "legendFormat": "{{dockerservice}}"
    }
   ]
  }
 ]
}