{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "traces",
     "gridPos": { "h": 20, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "operation": "POST::/api/v1/WatchlistMembers/Register",
       "query": "91f4fdad9071cc88",
       "service": "Api"
      }
     ]
    },
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 20, "w": 13, "x": 11, "y": 1 },
     "targets": [
      { "service": "Api" }
     ]
    }
   ]
  },
  { "title": "SF Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "SF Services logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{hostname=\"$hostname\", application=\"smartface\",structured=\"true\"} | json | line_format \"{{.ServiceName}} {{._mt}} {{._x}}\""
    },
    {
     "expr": "{hostname=\"$hostname\", application=\"smartface\",structured=\"false\"} | line_format \"{{.composeservice}} {{__line__}}\""
    }
   ]
  },
  {
   "title": "ZeroMQ notifications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(smartface_zeromq_notifications_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ZeroMQ pings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(smartface_zeromq_pings_total{hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "RPC requests from API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(rpc_client_duration_ms_count{hostname=\"$hostname\"}[$__rate_interval])) by (rpc_operation, processing_unit)",
     "legendFormat": "{{rpc_operation}}-{{processing_unit}}"
    }
   ]
  },
  {
   "title": "SF Services CPU usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(irate(container_cpu_usage_seconds_total{hostname=\"$hostname\", application=\"smartface\"}[1m])) by (composeservice)",
     "legendFormat": "{{dockerservice}}"
    }
   ]
  },
  {
   "title": "SF Services memory usage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{hostname=\"$hostname\", application=\"smartface\"}",
     "legendFormat": "{{composeservice}}"
    }
   ]
  },
  {
   "title": "Log volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({hostname=\"$hostname\", application=\"smartface\"}[1m])) ",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "SF Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "SF Dependencies logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "{hostname=\"$hostname\", application=\"smartface_dependencies\"} | regexp \"^(?P<line>.*)$\" | line_format \"{{.composeservice}} {{.line}}\""
      }
     ]
    },
    {
     "title": "SF Dependencies CPU usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * sum(rate(container_cpu_usage_seconds_total{hostname=\"$hostname\", application=\"smartface_dependencies\"}[1m])) by (composeservice)",
       "legendFormat": "{{dockerservice}}"
      }
     ]
    },
    {
     "title": "SF Dependencies memory usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{hostname=\"$hostname\", application=\"smartface_dependencies\"}",
       "legendFormat": "{{composeservice}}"
      }
     ]
    }
   ]
  },
  { "title": "Node status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Node CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{hostname=\"$hostname\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{hostname=\"$hostname\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * node_memory_MemAvailable_bytes{hostname=\"$hostname\"} / node_memory_MemTotal_bytes{hostname=\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\"} - node_memory_MemAvailable_bytes{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Node disk usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 13, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{hostname=\"$hostname\", fstype!~\"^(tmpfs|devtmpfs)$\"} - node_filesystem_free_bytes{hostname=\"$hostname\", fstype!~\"^(tmpfs|devtmpfs)$\"}) / node_filesystem_size_bytes{hostname=\"$hostname\",fstype!~\"^(tmpfs|devtmpfs)$\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}