services:
  detector:
    image: ${REGISTRY}sf-detector:${SF_VERSION}
    container_name: SFDetectCpu
    labels:
      application: smartface
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  extractor:
    image: ${REGISTRY}sf-extractor:${SF_VERSION}
    container_name: SFExtractCpu
    labels:
      application: smartface
      scrapeMetrics: true
    expose:
      - 4318
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  matcher:
    image: ${REGISTRY}sf-matcher:${SF_VERSION}
    container_name: SFWatchlistMatcher
    labels:
      application: smartface
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    cpuset: "0"

  liveness:
    image: ${REGISTRY}sf-liveness:${SF_VERSION}
    container_name: SFLiveness
    labels:
      application: smartface
      scrapeMetrics: true
    expose:
      - 4318  
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  watchlist-api:
    image: ${REGISTRY}sf-api:${SF_VERSION}
    container_name: SFWatchlistApi
    labels:
      application: smartface
      scrapeMetrics: true
    expose:
      - 4318
    ports:
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - MQTT__Hostname
      - MQTT__Username
      - MQTT__Password
      - MQTT__Port
      - MQTT__UseSsl
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - NoSqlDataStorageDisabled
      - FeatureManagement__Watchlist=true
      - FeatureManagement__Full=false
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  object-detector:
    image: ${REGISTRY}sf-object-detector:${SF_VERSION}
    container_name: SFObjectDetectorCpu
    labels:
      application: smartface
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  palm-detector:
    image: ${REGISTRY}sf-palm-detector:${SF_VERSION}
    container_name: SFPalmDetectCpu
    labels:
      application: smartface
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  palm-extractor:
    image: ${REGISTRY}sf-palm-extractor:${SF_VERSION}
    container_name: SFPalmExtractCpu
    labels:
      application: smartface
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  sf-station:
    image: ${REGISTRY}sf-station:${SFS_VERSION}
    container_name: SFStation
    labels:
      application: smartface
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file: .env.sfstation
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  sf-graphql-api:
    image: ${REGISTRY}sf-graphql-api:${SF_VERSION}
    container_name: SFGraphQLApi
    labels:
      application: smartface
      scrapeMetrics: true
    ports:
      # we forward the configured ports to default SF ports
      - 8097:${Hosting__Port}
    expose:
      - 4318
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - RabbitMQ__VirtualHost
      - RabbitMQ__UseSsl
      - MQTT__Hostname
      - MQTT__Username
      - MQTT__Password
      - MQTT__Port
      - MQTT__UseSsl
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log_RollingFile_Enabled=false
      - AppSettings__Log_JsonConsole_Enabled
      - Tracing__Enabled
      - OTEL_TRACES_SAMPLER
      - OTEL_TRACES_SAMPLER_ARG
      - OTEL_EXPORTER_OTLP_ENDPOINT
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

networks:
  default:
    name: sf-network
    external: true
