auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

ingester:
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: "2020-05-15"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    s3: http://minioadmin:minioadmin@obsminio:9000/loki
    s3forcepathstyle: true
    insecure: true

compactor:
  retention_enabled: true
  working_directory: /loki/compactor
  compaction_interval: 5m
  delete_request_store: filesystem

limits_config:
  retention_period: 744h
