version: '3.4'
services:
  detector:
    image: ${REGISTRY}sf-detector:${SF_VERSION}
    container_name: SFDetectCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
         
  extractor:
    image: ${REGISTRY}sf-extractor:${SF_VERSION}
    container_name: SFExtractCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
      
  matcher:
    image: ${REGISTRY}sf-matcher:${SF_VERSION}
    container_name: SFWatchlistMatcher
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
  
  liveness:
    image: ${REGISTRY}sf-liveness:${VERSION}
    container_name: SFLiveness
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "lic-volume:/etc/innovatrics/"    
      
  watchlist-api:
    image: ${REGISTRY}sf-watchlist-api:${SF_VERSION}
    container_name: SFWatchlistApi
    ports: 
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - Database__DbEngine
      - ConnectionStrings__CoreDbContext
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - S3Bucket__BucketName
      - S3Bucket__AccessKey
      - S3Bucket__SecretKey
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
      

networks:
  default:
    external:
      name: sf-network