version: '3.4'
services:
  sf-base:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    container_name: SFBase
    command: --serviceName SFBase
    ports: 
      - 2406:2406
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-group:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    container_name: SFGroup
    command: --serviceName SFGroup
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-1:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    container_name: SFCam1
    command: --serviceName SFCam1
    ports: 
      - 30001:30001
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - GstPipelineTemplate
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-2:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    container_name: SFCam2
    command: --serviceName SFCam2
    ports: 
      - 30002:30002
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - GstPipelineTemplate
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-nx:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    # Guid needs to match ServiceInstallNames.NX_TEST_CAMERA_GUID
    container_name: 53b4d78e-323f-4a0f-aa6d-99c464448b6d
    command: --serviceName 53b4d78e-323f-4a0f-aa6d-99c464448b6d
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  api:
    image: ${REGISTRY}sf-jetson-api:${JETSON_VERSION}
    privileged: true
    container_name: SFApi
    ports:
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  odata-api:
    image: ${REGISTRY}sf-jetson-odata-api:${JETSON_VERSION}
    privileged: true
    container_name: SFODataApi
    ports:
      # we forward the configured ports to default SF ports
      - 8099:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  detector-cpu:
    image: ${REGISTRY}sf-jetson-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFDetectCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  detector-gpu:
    image: ${REGISTRY}sf-jetson-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFDetectGpu
    command: --gpu=true
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - Gpu__GpuEnabled=true
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  pedestrian-detector-cpu:
    image: ${REGISTRY}sf-jetson-pedestrian-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFPedestrianDetectCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  pedestrian-detector-gpu:
    image: ${REGISTRY}sf-jetson-pedestrian-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFPedestrianDetectGpu
    command: --gpu=true
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - Gpu__GpuEnabled=true
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  extractor-cpu:
    image: ${REGISTRY}sf-jetson-extractor:${JETSON_VERSION}
    privileged: true
    container_name: SFExtractCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  extractor-gpu:
    image: ${REGISTRY}sf-jetson-extractor:${JETSON_VERSION}
    privileged: true
    container_name: SFExtractGpu
    command: --gpu=true
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - Gpu__GpuEnabled=true
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  matcher:
    image: ${REGISTRY}sf-jetson-matcher:${JETSON_VERSION}
    privileged: true
    container_name: SFWatchlistMatcher
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  face-matcher:
    image: ${REGISTRY}sf-jetson-face-matcher:${JETSON_VERSION}
    privileged: true
    container_name: SFFaceMatcher
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  liveness-cpu:
    image: ${REGISTRY}sf-jetson-liveness:${JETSON_VERSION}
    privileged: true
    container_name: SFLivenessCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  liveness-gpu:
    image: ${REGISTRY}sf-jetson-liveness:${JETSON_VERSION}
    privileged: true
    container_name: SFLivenessGpu
    command: --gpu=true
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - Gpu__GpuEnabled=true
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  video-aggregator:
    image: ${REGISTRY}sf-jetson-video-aggregator:${JETSON_VERSION}
    privileged: true
    container_name: SFVideoDataAggregator
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  video-collector:
    image: ${REGISTRY}sf-jetson-video-collector:${JETSON_VERSION}
    privileged: true
    container_name: SFVideoDataCollector
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  video-reader:
    image: ${REGISTRY}sf-jetson-video-reader:${JETSON_VERSION}
    privileged: true
    container_name: SFVideoReader
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia
    
  access-controller:
    image: ${REGISTRY}sf-access-controller:${AC_VERSION}
    privileged: true
    container_name: SFAccessController
    ports:
      # we forward the configured ports to default SF ports
      - 5050:${Hosting__Port}
    environment:
      - RabbitMq__HostName=${RabbitMQ__Hostname}
      - RabbitMq__UserName=${RabbitMQ__Username}
      - RabbitMq__Password=${RabbitMQ__Password}
      - RabbitMq__Port=${RabbitMQ__Port}
      - Kestrel__EndPoints__Http__Url=${Hosting__Host}:${Hosting__Port}

networks:
  default:
    external:
      name: sf-network
