version: "3.4"
services:
  sf-base:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    container_name: SFBase
    restart: unless-stopped
    command: --serviceName SFBase
    ports:
      - 2406:2406
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-group:
    image: ${REGISTRY}sf-jetson-base:${JETSON_VERSION}
    privileged: true
    container_name: SFGroup
    restart: unless-stopped
    command: --serviceName SFGroup
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-1:
    image: ${REGISTRY}sf-jetson-cam:${JETSON_VERSION}
    privileged: true
    container_name: SFCam1
    restart: unless-stopped
    command: --serviceName SFCam1
    ports:
      - 30001:30001
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - GstPipelineTemplate=${GstPipelineTemplate_Jetson}
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  sf-cam-2:
    image: ${REGISTRY}sf-jetson-cam:${JETSON_VERSION}
    privileged: true
    container_name: SFCam2
    restart: unless-stopped
    command: --serviceName SFCam2
    ports:
      - 30002:30002
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - GstPipelineTemplate=${GstPipelineTemplate_Jetson}
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  sf-cam-nx:
    image: ${REGISTRY}sf-jetson-cam:${JETSON_VERSION}
    privileged: true
    # Guid needs to match ServiceInstallNames.NX_TEST_CAMERA_GUID
    container_name: 53b4d78e-323f-4a0f-aa6d-99c464448b6d
    restart: unless-stopped
    command: --serviceName 53b4d78e-323f-4a0f-aa6d-99c464448b6d
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  api:
    image: ${REGISTRY}sf-jetson-api:${JETSON_VERSION}
    privileged: true
    container_name: SFApi
    restart: unless-stopped
    ports:
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-graphql-api:
    image: ${REGISTRY}sf-jetson-graphql-api:${JETSON_VERSION}
    container_name: SFGraphQLApi
    restart: unless-stopped
    ports:
      # we forward the configured ports to default SF ports
      - 8097:${Hosting__Port}
    environment:
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - AppSettings__Log_RabbitMq_Enabled

  odata-api:
    image: ${REGISTRY}sf-jetson-odata-api:${JETSON_VERSION}
    privileged: true
    container_name: SFODataApi
    restart: unless-stopped
    ports:
      # we forward the configured ports to default SF ports
      - 8099:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
      - Metrics__PROMETHEUS_METRIC_SERVER_HOSTNAME
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  detector-cpu:
    image: ${REGISTRY}sf-jetson-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFDetectCpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  detector-gpu:
    image: ${REGISTRY}sf-jetson-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFDetectGpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - Gpu__GpuEnabled=true
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  pedestrian-detector-cpu:
    image: ${REGISTRY}sf-jetson-pedestrian-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFPedestrianDetectCpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  pedestrian-detector-gpu:
    image: ${REGISTRY}sf-jetson-pedestrian-detector:${JETSON_VERSION}
    privileged: true
    container_name: SFPedestrianDetectGpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - Gpu__GpuEnabled=true
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  extractor-cpu:
    image: ${REGISTRY}sf-jetson-extractor:${JETSON_VERSION}
    privileged: true
    container_name: SFExtractCpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  extractor-gpu:
    image: ${REGISTRY}sf-jetson-extractor:${JETSON_VERSION}
    privileged: true
    container_name: SFExtractGpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - Gpu__GpuEnabled=true
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  matcher:
    image: ${REGISTRY}sf-jetson-matcher:${JETSON_VERSION}
    privileged: true
    container_name: SFWatchlistMatcher
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  face-matcher:
    image: ${REGISTRY}sf-jetson-face-matcher:${JETSON_VERSION}
    privileged: true
    container_name: SFFaceMatcher
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  liveness-cpu:
    image: ${REGISTRY}sf-jetson-liveness:${JETSON_VERSION}
    privileged: true
    container_name: SFLivenessCpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  liveness-gpu:
    image: ${REGISTRY}sf-jetson-liveness:${JETSON_VERSION}
    privileged: true
    container_name: SFLivenessGpu
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - Gpu__GpuEnabled=true
    # - Gpu__GpuNeuralRuntime=Tensor
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    # - "/var/tmp/innovatrics/tensor-rt:/var/tmp/innovatrics/tensor-rt"
    runtime: nvidia

  video-aggregator:
    image: ${REGISTRY}sf-jetson-video-aggregator:${JETSON_VERSION}
    privileged: true
    container_name: SFVideoDataAggregator
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  video-collector:
    image: ${REGISTRY}sf-jetson-video-collector:${JETSON_VERSION}
    privileged: true
    container_name: SFVideoDataCollector
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
      - S3Bucket__Endpoint
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  video-reader:
    image: ${REGISTRY}sf-jetson-video-reader:${JETSON_VERSION}
    privileged: true
    container_name: SFVideoReader
    restart: unless-stopped
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled=false
      - AppSettings__USE_JAEGER_APP_SETTINGS
      - JAEGER_AGENT_HOST
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  access-controller:
    image: ${REGISTRY}sf-access-controller:${AC_VERSION}
    privileged: true
    container_name: SFAccessController
    restart: unless-stopped
    ports:
      # we forward the configured ports to default SF ports
      - 5050:${Hosting__Port}
    environment:
      - RabbitMq__HostName=${RabbitMQ__Hostname}
      - RabbitMq__UserName=${RabbitMQ__Username}
      - RabbitMq__Password=${RabbitMQ__Password}
      - RabbitMq__Port=${RabbitMQ__Port}
      - Kestrel__EndPoints__Http__Url=${Hosting__Host}:${Hosting__Port}
    env_file: .env.sfac

  sf-station:
    image: ${REGISTRY}sf-station:${SFS_VERSION}
    container_name: SFStation
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file: .env.sfstation

networks:
  default:
    external:
      name: sf-network
