version: '3.4'
services:
  sf-base:
    image: ${REGISTRY}sf-jetson-base:${SF_VERSION}
    container_name: SFBase
    command: --serviceName SFBase
    ports: 
      - 2406:2406
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-group:
    image: ${REGISTRY}sf-jetson-base:${SF_VERSION}
    container_name: SFGroup
    command: --serviceName SFGroup
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-1:
    image: ${REGISTRY}sf-jetson-base:${SF_VERSION}
    container_name: SFCam1
    command: --serviceName SFCam1
    ports: 
      - 30001:30001
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - GstPipelineTemplate
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-2:
    image: ${REGISTRY}sf-jetson-base:${SF_VERSION}
    container_name: SFCam2
    command: --serviceName SFCam2
    ports: 
      - 30002:30002
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - GstPipelineTemplate
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  sf-cam-nx:
    image: ${REGISTRY}sf-jetson-base:${SF_VERSION}
    # Guid needs to match ServiceInstallNames.NX_TEST_CAMERA_GUID
    container_name: 53b4d78e-323f-4a0f-aa6d-99c464448b6d
    command: --serviceName 53b4d78e-323f-4a0f-aa6d-99c464448b6d
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  api:
    image: ${REGISTRY}sf-jetson-api:${SF_VERSION}
    container_name: SFApi
    ports:
      # we forward the configured ports to default SF ports
      - 8098:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  odata-api:
    image: ${REGISTRY}sf-jetson-odata-api:${SF_VERSION}
    container_name: SFODataApi
    ports:
      # we forward the configured ports to default SF ports
      - 8099:${Hosting__Port}
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - Hosting__Host
      - Hosting__Port
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  detector:
    image: ${REGISTRY}sf-jetson-detector:${SF_VERSION}
    container_name: SFDetectCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  pedestrian-detector:
    image: ${REGISTRY}sf-jetson-pedestrian-detector:${SF_VERSION}
    container_name: SFPedestrianDetectCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  extractor:
    image: ${REGISTRY}sf-jetson-extractor:${SF_VERSION}
    container_name: SFExtractCpu
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  matcher:
    image: ${REGISTRY}sf-jetson-matcher:${SF_VERSION}
    container_name: SFWatchlistMatcher
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  liveness:
    image: ${REGISTRY}sf-jetson-liveness:${SF_VERSION}
    container_name: SFLiveness
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  video-aggregator:
    image: ${REGISTRY}sf-jetson-video-aggregator:${SF_VERSION}
    container_name: SFVideoDataAggregator
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia

  video-collector:
    image: ${REGISTRY}sf-jetson-video-collector:${SF_VERSION}
    container_name: SFVideoDataCollector
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - ConnectionStrings__CoreDbContext
      - Database__DbEngine
      - AppSettings__Log-RollingFile-Enabled
      - S3Bucket__Endpoint
      - AppSettings__Log_RabbitMq_Enabled
      - NoSqlDataStorageDisabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"

  video-reader:
    image: ${REGISTRY}sf-jetson-video-reader:${SF_VERSION}
    container_name: SFVideoReader
    environment:
      - RabbitMQ__Hostname
      - RabbitMQ__Username
      - RabbitMQ__Password
      - RabbitMQ__Port
      - AppSettings__Log-RollingFile-Enabled
      - AppSettings__Log_RabbitMq_Enabled
    volumes:
      - "./iengine.lic:/etc/innovatrics/iengine.lic"
    runtime: nvidia
    
  access-controller:
    image: ${REGISTRY}sf-access-controller:${AC_VERSION}
    container_name: SFAccessController
    ports:
      # we forward the configured ports to default SF ports
      - 5050:${Hosting__Port}
    environment:
      - RabbitMq__HostName
      - RabbitMq__UserName
      - RabbitMq__Password
      - RabbitMq__Port
      - Kestrel__EndPoints__Http__Url=http://${Hosting__Host}:${Hosting__Port}

networks:
  default:
    external:
      name: sf-network
